spring.application.name=ORDER-SERVICE
server.port=8082

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# LoadBalancer
spring.cloud.loadbalancer.eager-load.clients=USER-SERVICE,PAYMENT-SERVICE

#-------------payment----------------
# RETRY
resilience4j.retry.instances.paymentRetry.max-attempts=3
resilience4j.retry.instances.paymentRetry.wait-duration=1s

# TIME LIMITER
resilience4j.timelimiter.instances.paymentTimeLimiter.timeout-duration=2s

# CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.permitted-number-of-calls-in-half-open-state=2

#---------user------------------
# Retry
resilience4j.retry.instances.userRetry.max-attempts=3
resilience4j.retry.instances.userRetry.wait-duration=1s

# TimeLimiter
resilience4j.timelimiter.instances.userTimeLimiter.timeout-duration=2s

# Circuit Breaker
resilience4j.circuitbreaker.instances.userCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.userCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userCircuitBreaker.permitted-number-of-calls-in-half-open-state=2